/*
 * This source file was generated by the Gradle 'init' task
 */
package org.chess;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ChessTest {
    @Test void appHasAGreeting() {
        Chess classUnderTest = new Chess();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
