/*
 * This source file was generated by the Gradle 'init' task
 */
package org.chess;

import org.chess.graphics.*;

public class Chess {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ChessModel model = new ChessModel();
        SwingChessView view = new SwingChessView();
        ChessController controller = new ChessController(view, model);
    }
}
